### ISSUE TITLE
Fun with Python

### ISSUE THREAD

**Issue by AKG1301** [Crio-Bytes/IBD-2022-Master-Repository#65]
**MicroByte Title:** Fun with Python

**Domain:** Python Skills

**Scope of learning for learners:** Coders will understand how we create Python scripts. how Python is helpful for routine tasks

**Activities:** Coders will understand how we create Python scripts. how Python is helpful for routine tasks

**Comment by AKG1301** [comment]
@prashanthlingala please assign this task to me

**Comment by prashanthlingala** [comment]
Done..please check
